management:
  security:
    enabled: false
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    jmx:
      enabled: false
    shutdown:
      enabled: true


spring:
  jmx:
    enabled: false
  sleuth:
    enabled: false
    sampler:
      percentage: 1.0
    log:
      json:
        enabled: true
  zipkin:
    enabled: false
  jpa:
    generate-ddl: true

#logging:
#  pattern:
#    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}]){yellow} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wex"


