##################################################################################################
# Productpage services
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: samples-bookinfo-productpage-v1
  namespace: flomesh-spring
  labels:
    app: productpage
    service: samples-bookinfo-productpage-v1
spec:
  ports:
    - port: 9080
      name: http
      targetPort: 9080
    - port: 9090
      name: sidecar
      targetPort: 9090
  selector:
    app: productpage
    version: v1
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: samples-bookinfo-productpage-v1
  namespace: flomesh-spring
  labels:
    app: productpage
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
      version: v1
  template:
    metadata:
      labels:
        app: productpage
        version: v1
        service: samples-bookinfo-productpage
#        sys: bookinfo-samples
      annotations:
        "flomesh.io/inject": "true"
    spec:
      initContainers:
        - name: check-config
          image: busybox:latest
          command: [ "/bin/sh", "-c" ]
          args:
            - |-
              until nc -vz samples-api-gateway-v1 10010; \
                do echo "Waiting for API Gateway ready ..."; \
                sleep 5; \
              done;
      containers:
        - name: app
          env:
            - name: SERVICES_DOMAIN
              value: flomesh-spring.svc
            - name: K8S_SAMPLES_API_GATEWAY_HOSTNAME
              value: samples-api-gateway-v1
            - name: K8S_SAMPLES_API_GATEWAY_PORT
              value: "10010"
            - name: _pod_ns
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: _pod_nodeName
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: _pod_name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: _pod_serviceName
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['service']
            - name: _pod_serviceVersion
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['version']
            - name: _pod_serviceFullName
              value: $(_pod_serviceName)-$(_pod_serviceVersion)
            - name: _pod_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: _pod_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: _pod_hostIP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          image: flomesh/samples-bookinfo-productpage:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9080
          resources:
            limits:
              memory: 300Mi
              cpu: 100m
---